server:
  port: 8081
spring:
  cloud: 
   gateway: 
    routes:
      - id: games
        uri: lb://games/
        predicates:
          - Path=/games/**
      - id: cart
        uri: lb://cart/
        predicates:
          - Path=/cart/**
      - id: cartCB
        uri: lb://cartCB/
        predicates:
          - Path=/cartCB/**          
